apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: my-app-db

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-db
  template:
    metadata:
      labels:
        app: my-app-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: myappdb
            - name: POSTGRES_USER
              value: myappuser
            - name: POSTGRES_PASSWORD
              value: myapppassword
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: my-app-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: python-backend
          image: nicourrrn/dyploma-python-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgres://myappuser:myapppassword@my-app-db:5432/myappdb
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
